const SEND_REQUEST_PROCESS_LOOP_INTERVAL = 3_000;
const BROWSER_RECONNECT_LOOP_INTERVAL = 10_000;
const QR_CONNECT_TIMEOUT = 30_000;

export {
  SEND_REQUEST_PROCESS_LOOP_INTERVAL,
  BROWSER_RECONNECT_LOOP_INTERVAL,
  QR_CONNECT_TIMEOUT,
};
